version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports: 
      - "3001:3001"
    volumes: 
      - .:/comedy_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      RAILS_ENV: development
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes: 
      - postgres_volume:/var/lib/postgresql/data
volumes:
  postgres_volume:
